<a href="https://colab.research.google.com/github/Asma-malica/DL/blob/main/DL_RNN_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
train_data = {
  'good': True,
  'bad': False,
  'happy': True,
  'sad': False,
  'not good': False,
  'not bad': True,
  'not happy': False,
  'not sad': True,
  'very good': True,
  'very bad': False,
  'very happy': True,
  'very sad': False,
  'i am happy': True,
  'this is good': True,
  'i am bad': False,
  'this is bad': False,
  'i am sad': False,
  'this is sad': False,
  'i am not happy': False,
  'this is not good': False,
  'i am not bad': True,
  'this is not sad': True,
  'i am very happy': True,
  'this is very good': True,
  'i am very bad': False,
  'this is very sad': False,
  'this is very happy': True,
  'i am good not bad': True,
  'this is good not bad': True,
  'i am bad not good': False,
  'i am good and happy': True,
  'this is not good and not happy': False,
  'i am not at all good': False,
  'i am not at all bad': True,
  'i am not at all happy': False,
  'this is not at all sad': True,
  'this is not at all happy': False,
  'i am good right now': True,
  'i am bad right now': False,
  'this is bad right now': False,
  'i am sad right now': False,
  'i was good earlier': True,
  'i was happy earlier': True,
  'i was bad earlier': False,
  'i was sad earlier': False,
  'i am very bad right now': False,
  'this is very good right now': True,
  'this is very sad right now': False,
  'this was bad earlier': False,
  'this was very good earlier': True,
  'this was very bad earlier': False,
  'this was very happy earlier': True,
  'this was very sad earlier': False,
  'i was good and not bad earlier': True,
  'i was not good and not happy earlier': False,
  'i am not at all bad or sad right now': True,
  'i am not at all good or happy right now': False,
  'this was not happy and not good earlier': False,
}

test_data = {
  'this is happy': True,
  'i am good': True,
  'this is not happy': False,
  'i am not good': False,
  'this is not bad': True,
  'i am not sad': True,
  'i am very good': True,
  'this is very bad': False,
  'i am very sad': False,
  'this is bad not good': False,
  'this is good and happy': True,
  'i am not good and not happy': False,
  'i am not at all sad': True,
  'this is not at all good': False,
  'this is not at all bad': True,
  'this is good right now': True,
  'this is sad right now': False,
  'this is very bad right now': False,
  'this was good earlier': True,
  'i was not happy and not good earlier': False,
}

In [ ]:
train_data.keys()

dict_keys(['good', 'bad', 'happy', 'sad', 'not good', 'not bad', 'not happy', 'not sad', 'very good', 'very bad', 'very happy', 'very sad', 'i am happy', 'this is good', 'i am bad', 'this is bad', 'i am sad', 'this is sad', 'i am not happy', 'this is not good', 'i am not bad', 'this is not sad', 'i am very happy', 'this is very good', 'i am very bad', 'this is very sad', 'this is very happy', 'i am good not bad', 'this is good not bad', 'i am bad not good', 'i am good and happy', 'this is not good and not happy', 'i am not at all good', 'i am not at all bad', 'i am not at all happy', 'this is not at all sad', 'this is not at all happy', 'i am good right now', 'i am bad right now', 'this is bad right now', 'i am sad right now', 'i was good earlier', 'i was happy earlier', 'i was bad earlier', 'i was sad earlier', 'i am very bad right now', 'this is very good right now', 'this is very sad right now', 'this was bad earlier', 'this was very good earlier', 'this was very bad earlier', 'this

In [ ]:
list(set("a a b a d c".split(' ')))

['d', 'b', 'a', 'c']

In [ ]:
vocab = list(set([w for text in train_data.keys() for w in text.split(' ')]))
vocab_size = len(vocab)
print('%d unique words found' % vocab_size) # 18 unique words found
print(vocab)


18 unique words found
['right', 'was', 'bad', 'sad', 'or', 'and', 'happy', 'is', 'now', 'very', 'this', 'earlier', 'all', 'am', 'not', 'at', 'good', 'i']


In [ ]:
# Assign indices to each word.
word_to_idx = { w: i for i, w in enumerate(vocab) }
idx_to_word = { i: w for i, w in enumerate(vocab) }
print(word_to_idx['good']) # 16 (this may change)
print(idx_to_word[0]) # sad (this may change)

16
right


In [ ]:
idx_to_word

{0: 'right',
 1: 'was',
 2: 'bad',
 3: 'sad',
 4: 'or',
 5: 'and',
 6: 'happy',
 7: 'is',
 8: 'now',
 9: 'very',
 10: 'this',
 11: 'earlier',
 12: 'all',
 13: 'am',
 14: 'not',
 15: 'at',
 16: 'good',
 17: 'i'}

In [ ]:
import numpy as np

def createInputs(text):
  '''
  Returns an array of one-hot vectors representing the words
  in the input text string.
  - text is a string
  - Each one-hot vector has shape (vocab_size, 1)
  '''
  inputs = []
  for w in text.split(' '):
    v = np.zeros((vocab_size, 1))
    v[word_to_idx[w]] = 1
    inputs.append(v)
  return inputs

In [ ]:
createInputs("i am very happy")

[array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.]]),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],


In [ ]:
testip = "i am very happy"
for txt, vec in zip(testip.split(" "), createInputs(testip)):
  print(txt, list(vec))

i [array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([1.])]
am [array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([1.]), array([0.]), array([0.]), array([0.]), array([0.])]
very [array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([1.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.])]
happy [array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([1.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.])]


In [ ]:
import numpy as np
from numpy.random import randn

In [ ]:
class RNN:
  # A Vanilla Recurrent Neural Network.

  def __init__(self, input_size, output_size, hidden_size=64):
    # Weights
    self.Whh = randn(hidden_size, hidden_size) / 1000
    self.Wxh = randn(hidden_size, input_size) / 1000
    self.Why = randn(output_size, hidden_size) / 1000

    # Biases
    self.bh = np.zeros((hidden_size, 1))
    self.by = np.zeros((output_size, 1))

  def forward(self, inputs):

    h = np.zeros((self.Whh.shape[0], 1))

    self.last_inputs = inputs
    self.last_hs = { 0: h }

    for i, x in enumerate(inputs):
      h = np.tanh(self.Wxh @ x + self.Whh @ h + self.bh)
      self.last_hs[i + 1] = h

    y = self.Why @ h + self.by
    return y, h

  def backprop(self, d_y, learn_rate=2e-2):
      '''
      Perform a backward pass of the RNN.
      - d_y (dL/dy) has shape (output_size, 1).
      - learn_rate is a float.
      '''
      n = len(self.last_inputs)

      # Calculate dL/dWhy and dL/dby.
      d_Why = d_y @ self.last_hs[n].T
      d_by = d_y

      # Initialize dL/dWhh, dL/dWxh, and dL/dbh to zero.
      d_Whh = np.zeros(self.Whh.shape)
      d_Wxh = np.zeros(self.Wxh.shape)
      d_bh = np.zeros(self.bh.shape)

      # Calculate dL/dh for the last h.
      d_h = self.Why.T @ d_y

      # Backpropagate through time.
      for t in reversed(range(n)):
        # An intermediate value: dL/dh * (1 - h^2)
        temp = ((1 - self.last_hs[t + 1] ** 2) * d_h)

        # dL/db = dL/dh * (1 - h^2)
        d_bh += temp

        # dL/dWhh = dL/dh * (1 - h^2) * h_{t-1}
        d_Whh += temp @ self.last_hs[t].T

        # dL/dWxh = dL/dh * (1 - h^2) * x
        d_Wxh += temp @ self.last_inputs[t].T

        # Next dL/dh = dL/dh * (1 - h^2) * Whh
        d_h = self.Whh @ temp

      # Clip to prevent exploding gradients.
      for d in [d_Wxh, d_Whh, d_Why, d_bh, d_by]:
        np.clip(d, -1, 1, out=d)

      # Update weights and biases using gradient descent.
      self.Whh -= learn_rate * d_Whh
      self.Wxh -= learn_rate * d_Wxh
      self.Why -= learn_rate * d_Why
      self.bh -= learn_rate * d_bh
      self.by -= learn_rate * d_by

In [ ]:
rnn = RNN(vocab_size, 2) # vocab_size is 18

In [ ]:
rnn.__dict__

{'Whh': array([[ 5.52537737e-04, -6.84751501e-04,  9.64281671e-04, ...,
          9.36224164e-04, -4.78458720e-04,  2.12001176e-03],
        [-4.85243684e-04,  1.45699264e-03, -1.76670018e-03, ...,
          7.88617773e-05,  3.18593020e-04,  1.56132555e-03],
        [ 4.11760330e-04, -1.19006276e-03,  1.27835250e-03, ...,
         -1.07124853e-03, -8.92381717e-04,  1.45151677e-03],
        ...,
        [ 1.11399594e-03,  1.02285652e-03,  6.49576557e-04, ...,
         -1.43846380e-04,  1.28822639e-06,  1.49417110e-03],
        [-4.19547318e-04, -5.02569847e-04, -5.37967927e-04, ...,
         -5.66211188e-04, -5.14613546e-04,  7.91233579e-04],
        [-7.73536497e-04, -4.73698474e-05,  1.35956501e-03, ...,
          1.92222268e-04,  1.50529505e-03, -1.12680146e-03]]),
 'Wxh': array([[ 9.57897791e-04,  1.40290715e-03, -5.46528045e-04, ...,
         -8.08109095e-04,  1.13770073e-03,  6.59568802e-04],
        [-1.28865809e-04,  1.00343125e-03,  4.22948077e-04, ...,
          1.50238755e-04

In [ ]:
inputs = createInputs("i am very happy")
inputs

[array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.]]),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],


In [ ]:
def softmax(xs):
  # Applies the Softmax Function to the input array.
  return np.exp(xs) / sum(np.exp(xs))

In [ ]:
rnn.forward(inputs) # gives y and h

(array([[ 9.85420847e-06],
        [-2.59041389e-06]]),
 array([[-1.05003651e-03],
        [ 3.70752977e-05],
        [ 1.23410014e-03],
        [ 8.74187971e-04],
        [ 2.80728474e-04],
        [-1.52966720e-05],
        [-3.24526857e-04],
        [-1.28778820e-03],
        [ 4.66674197e-04],
        [ 2.25427520e-04],
        [ 4.52859613e-04],
        [-8.04507647e-04],
        [-2.04212625e-03],
        [-8.22815330e-04],
        [ 7.88733091e-05],
        [-8.31181884e-04],
        [-1.61596877e-05],
        [ 6.55107181e-04],
        [ 8.77498372e-05],
        [-4.25356751e-04],
        [ 1.12359997e-03],
        [-6.34871387e-04],
        [-4.65404208e-04],
        [ 3.08730167e-04],
        [-1.36033763e-03],
        [-1.02303790e-03],
        [ 1.69894721e-04],
        [ 8.18987373e-04],
        [ 1.57651383e-03],
        [-1.24984489e-03],
        [-1.08509701e-04],
        [ 1.26931557e-04],
        [-1.81762859e-03],
        [ 1.19300698e-03],
        [ 2.70284813e-04],

In [ ]:
rnn.forward(inputs)[0] # y alone

array([[ 9.85420847e-06],
       [-2.59041389e-06]])

In [ ]:
softmax(rnn.forward(inputs)[0])

array([[0.50000311],
       [0.49999689]])

In [ ]:
inputs = createInputs("i am happy")
softmax(rnn.forward(inputs)[0])

array([[0.50000309],
       [0.49999691]])

In [ ]:
# sad [1, 0]
# happy [0, 1]

In [ ]:
import random

def processData(data, backprop=True):
  '''
  Returns the RNN's loss and accuracy for the given data.
  - data is a dictionary mapping text to True or False.
  - backprop determines if the backward phase should be run.
  '''
  items = list(data.items())
  random.shuffle(items)

  loss = 0
  num_correct = 0

  for x, y in items:
    inputs = createInputs(x)
    target = int(y)

    # Forward
    out, _ = rnn.forward(inputs)
    probs = softmax(out)

    # Calculate loss / accuracy
    loss -= np.log(probs[target])
    num_correct += int(np.argmax(probs) == target)

    if backprop:
      # Build dL/dy
      d_L_d_y = probs
      d_L_d_y[target] -= 1

      # Backward
      rnn.backprop(d_L_d_y)

  return loss / len(data), num_correct / len(data)

In [ ]:
train_data

{'good': True,
 'bad': False,
 'happy': True,
 'sad': False,
 'not good': False,
 'not bad': True,
 'not happy': False,
 'not sad': True,
 'very good': True,
 'very bad': False,
 'very happy': True,
 'very sad': False,
 'i am happy': True,
 'this is good': True,
 'i am bad': False,
 'this is bad': False,
 'i am sad': False,
 'this is sad': False,
 'i am not happy': False,
 'this is not good': False,
 'i am not bad': True,
 'this is not sad': True,
 'i am very happy': True,
 'this is very good': True,
 'i am very bad': False,
 'this is very sad': False,
 'this is very happy': True,
 'i am good not bad': True,
 'this is good not bad': True,
 'i am bad not good': False,
 'i am good and happy': True,
 'this is not good and not happy': False,
 'i am not at all good': False,
 'i am not at all bad': True,
 'i am not at all happy': False,
 'this is not at all sad': True,
 'this is not at all happy': False,
 'i am good right now': True,
 'i am bad right now': False,
 'this is bad right now': Fa

In [ ]:
# Training loop
for epoch in range(1000):
  train_loss, train_acc = processData(train_data)

  if epoch % 100 == 99:
    print('--- Epoch %d' % (epoch + 1))
    print('Train:\tLoss %.3f | Accuracy: %.3f' % (train_loss, train_acc))

    test_loss, test_acc = processData(test_data, backprop=False)
    print('Test:\tLoss %.3f | Accuracy: %.3f' % (test_loss, test_acc))

--- Epoch 100
Train:	Loss 0.689 | Accuracy: 0.552
Test:	Loss 0.697 | Accuracy: 0.500
--- Epoch 200
Train:	Loss 0.674 | Accuracy: 0.621
Test:	Loss 0.718 | Accuracy: 0.550
--- Epoch 300
Train:	Loss 0.666 | Accuracy: 0.638
Test:	Loss 0.696 | Accuracy: 0.500
--- Epoch 400
Train:	Loss 0.038 | Accuracy: 1.000
Test:	Loss 0.037 | Accuracy: 1.000
--- Epoch 500
Train:	Loss 0.008 | Accuracy: 1.000
Test:	Loss 0.010 | Accuracy: 1.000
--- Epoch 600
Train:	Loss 0.004 | Accuracy: 1.000
Test:	Loss 0.006 | Accuracy: 1.000
--- Epoch 700
Train:	Loss 0.003 | Accuracy: 1.000
Test:	Loss 0.004 | Accuracy: 1.000
--- Epoch 800
Train:	Loss 0.002 | Accuracy: 1.000
Test:	Loss 0.003 | Accuracy: 1.000
--- Epoch 900
Train:	Loss 0.002 | Accuracy: 1.000
Test:	Loss 0.002 | Accuracy: 1.000
--- Epoch 1000
Train:	Loss 0.001 | Accuracy: 1.000
Test:	Loss 0.002 | Accuracy: 1.000


In [ ]:
rnn.__dict__

{'Whh': array([[ 6.81811402e-02,  9.42981847e-03, -9.18984493e-02, ...,
         -2.05380060e-03,  6.84113655e-02, -1.36827047e-03],
        [-1.21589497e-02, -3.88313763e-02,  3.59033971e-02, ...,
          5.28544763e-03, -5.53230109e-02, -8.59003343e-03],
        [-1.02030574e-01, -8.98915914e-03,  1.33398697e-01, ...,
          2.32236258e-03, -8.64793312e-02,  1.62981210e-02],
        ...,
        [ 2.15107061e-02,  1.28464411e-02, -2.37311500e-02, ...,
          1.38111724e-03,  3.42305560e-02,  7.64609399e-03],
        [ 7.74561023e-02,  3.16350945e-03, -9.81828652e-02, ...,
         -4.77691598e-03,  6.24572100e-02,  7.44727685e-04],
        [-6.88381088e-02, -3.82135237e-02,  9.40763213e-02, ...,
          5.15795351e-03, -7.93483920e-02,  5.85592146e-05]]),
 'Wxh': array([[-0.04253966,  0.03912658,  0.10729557, ...,  0.02970084,
         -0.25719153,  0.04192155],
        [-0.03053011,  0.02967678, -0.17116554, ...,  0.05905256,
          0.10667253, -0.02062638],
        [ 0

In [ ]:
inputs = createInputs("i am happy")
out, _ = rnn.forward(inputs)
softmax(out)

array([[0.00255556],
       [0.99744444]])

In [ ]:
inputs = createInputs("i am sad")
out, _ = rnn.forward(inputs)
softmax(out)

array([[0.99859661],
       [0.00140339]])

In [ ]:
inputs = createInputs("i am great")
out, _ = rnn.forward(inputs)
softmax(out)

# Out of Vocab Word

KeyError: 'great'