<a href="https://colab.research.google.com/github/Asma-malica/DL/blob/main/DL_RNN_from_scratch_SpamDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/soaicbe/ml/master/spam.csv")
data

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
data.isnull().sum()

Category    0
Message     0
dtype: int64

In [ ]:
# list(set("a a b a d c".split(' ')))
Message = list(data.Message.str.lower())


In [ ]:
import string
def rm_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [ ]:
for i in range(len(Message)):
  Message[i] = rm_punc(Message[i])

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(Message,data['Category'],test_size=0.2,random_state=0)
Msg1 = []
Msg2 = []

import spacy
nlp = spacy.load("en_core_web_sm")

for i in range(len(x_train)):
  x = nlp(x_train[i])
  x_train[i]= ' '.join([token.text for token in x if not token.is_stop])



In [ ]:
x_train

['m good movie ok leave hourish',
 'wereare free nalla adi entey nattil kittum',
 'emigrated ok maybe 530 bit hopeful',
 'got home babe awake',
 'kay',
 'm workin job',
 'said matter mind saying matter',
 'oh yeah diet flew window',
 'sorry got things pub later',
 'ill evening ill ideas',
 'dear reache room',
 'got looks scrumptious daddy wants eat night long',
 'badrith chennaii surely pick usno competition',
 'da car park',
 'okay soon best',
 'yar ill thk sorts funny things',
 'yup izzit raining heavily cos m e mrt nt c outside',
 'way ur home',
 's ok popped ask bout said d tonght wen girl comes',
 'talk g x',
 'cool tyler gon na buy drop place later tonight total order quarter got',
 '5 2 work timing',
 'yup m free',
 'maybe westshore hyde park village place near house',
 '  said woke  ',
 'drama plsi family struggling hot sun strange placeno reason ego going invited actually necessity gowait reppurcussions',
 's coming hill monster hope great day things r going fine busy',
 'comp

In [ ]:
# import spacy
# nlp = spacy.load("en_core_web_sm")
for i in range(len(x_test)):
  x1 = nlp(x_test[i])
  x_test[i]= ' '.join([token.text for token in x1 if not token.is_stop])

In [ ]:
x_test

['storming msg wen u lift d phne u hello u knw wt d real meaning hello     d girl     yes u knw dat girl margaret hello d girlfrnd f grahmbell invnted telphone      moralone 4get d person bt girlfrnd g o o d n g h t   ',
 'forwarded 448712404000please 08712404000 immediately urgent message waiting',
 've sorta blown couple times recently d text blue looking weed',
 'sir goodmorning free',
 'come alivebetter correct good looking figure',
 'housemaid murderer coz man murdered   ltgt th january public holiday govtinstituitions closedincluding post officeunderstand',
 'hot n horny willing live local   text reply hear strt 150p msg netcollex ltdhelpdesk 02085076972 reply stop end',
 'sorry ill later meeting thing related trade arul ltgt',
 'oh sorry',
 'hey hunonbus goin 2 meet wants 2go 4a meal donyt feel like cuz 2 bus homebut s sweet latelyxxx',
 'stupid auto correct phone',
 'oh k kbut big hitteranyway good',
 'roger we‘re probably going rem 20',
 'ya ok vikky vl c witin   ltgt mins il 

In [ ]:
Msg1 = list(set(x_train))
train_size =len(Msg1)
train_size

4155

In [ ]:
# vocab = list(set([w for text in train_data.keys() for w in text.split(' ')]))
# vocab_size = len(vocab)
# print('%d unique words found' % vocab_size) # 18 unique words found
# print(vocab)

# vocab = list(set(filtered_words))
# vocab

In [ ]:
# # Assign indices to each word.
word_to_idx1 = { w: i for i, w in enumerate(Msg1) }
idx_to_word1 = { i: w for i, w in enumerate(Msg1) }
print(word_to_idx1['ok']) # 16 (this may change)
print(idx_to_word1[0]) # sad (this may change)



772



In [ ]:
idx_to_word1

{0: '',
 1: 'deep sigh   miss    surprised nt gone net cafe   nt miss',
 2: 'printer cool mean groovy wine groovying',
 3: 'damn poor zac nt stand chance',
 4: 'meant money enters account bank remove flat rate transfered   ltgt   account   ltgt dollars got removed banks differ charges differbe sure trust 9ja person sending account details cos',
 5: 'sorry flaked night shits seriously goin roommate tonight',
 6: 'alrite hunnywot u 2 2nite nt end goin town jus da pub instead jus chillin da mo bedroomlove jen xxx',
 7: 'wylie tampa sarasota',
 8: 'need ke qi ü bored izzit y suddenly thk',
 9: 'nt necessarily expect m headin',
 10: 'hmm   bits pieces lol   sighs',
 11: 'u studying sch going home ill b going 2 sch later',
 12: 'u download fring app',
 13: 'want new video phone750 anytime network mins 150 text pounds week 08000776320 reply delivery tomorrow',
 14: 'number u live 11',
 15: 'later nt network urgnt sms',
 16: 'u r subscribed 2 textcomp 250 wkly comp 1st wks free question follow

In [ ]:
import numpy as np

def createInputs(text):
  '''
  Returns an array of one-hot vectors representing the words
  in the input text string.
  - text is a string
  - Each one-hot vector has shape (vocab_size, 1)
  '''
  inputs = []
  for w in text.split(' '):
    v = np.zeros((train_size, 1))
    v[word_to_idx1.get(w, 0)] = 1
    inputs.append(v)
  return inputs

In [ ]:
createInputs("£ 400 xmas reward waiting computer randomly picked loyal mobile customers receive £ 400 reward 09066380611")

[array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1

In [ ]:
testip = "£ 400 xmas reward waiting computer randomly picked loyal mobile customers receive £ 400 reward 09066380611"
for txt, vec in zip(testip.split(" "), createInputs(testip)):
  print(txt, list(vec))

£ [array([1.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.

In [ ]:
import numpy as np
from numpy.random import randn

In [ ]:
class RNN:
  # A Vanilla Recurrent Neural Network.

  def __init__(self, input_size, output_size, hidden_size=64):
    # Weights
    self.Whh = randn(hidden_size, hidden_size) / 1000
    self.Wxh = randn(hidden_size, input_size) / 1000
    self.Why = randn(output_size, hidden_size) / 1000

    # Biases
    self.bh = np.zeros((hidden_size, 1))
    self.by = np.zeros((output_size, 1))

  def forward(self, inputs):

    h = np.zeros((self.Whh.shape[0], 1))

    self.last_inputs = inputs
    self.last_hs = { 0: h }

    for i, x in enumerate(inputs):
      h = np.tanh(self.Wxh @ x + self.Whh @ h + self.bh)
      self.last_hs[i + 1] = h

    y = self.Why @ h + self.by
    return y, h

  def backprop(self, d_y, learn_rate=2e-2):
      '''
      Perform a backward pass of the RNN.
      - d_y (dL/dy) has shape (output_size, 1).
      - learn_rate is a float.
      '''
      n = len(self.last_inputs)

      # Calculate dL/dWhy and dL/dby.
      d_Why = d_y @ self.last_hs[n].T
      d_by = d_y

      # Initialize dL/dWhh, dL/dWxh, and dL/dbh to zero.
      d_Whh = np.zeros(self.Whh.shape)
      d_Wxh = np.zeros(self.Wxh.shape)
      d_bh = np.zeros(self.bh.shape)

      # Calculate dL/dh for the last h.
      d_h = self.Why.T @ d_y

      # Backpropagate through time.
      for t in reversed(range(n)):
        # An intermediate value: dL/dh * (1 - h^2)
        temp = ((1 - self.last_hs[t + 1] ** 2) * d_h)

        # dL/db = dL/dh * (1 - h^2)
        d_bh += temp

        # dL/dWhh = dL/dh * (1 - h^2) * h_{t-1}
        d_Whh += temp @ self.last_hs[t].T

        # dL/dWxh = dL/dh * (1 - h^2) * x
        d_Wxh += temp @ self.last_inputs[t].T

        # Next dL/dh = dL/dh * (1 - h^2) * Whh
        d_h = self.Whh @ temp

      # Clip to prevent exploding gradients.
      for d in [d_Wxh, d_Whh, d_Why, d_bh, d_by]:
        np.clip(d, -1, 1, out=d)

      # Update weights and biases using gradient descent.
      self.Whh -= learn_rate * d_Whh
      self.Wxh -= learn_rate * d_Wxh
      self.Why -= learn_rate * d_Why
      self.bh -= learn_rate * d_bh
      self.by -= learn_rate * d_by

In [ ]:
rnn = RNN(train_size, 2) # vocab_size is 18

In [ ]:
rnn.__dict__

{'Whh': array([[ 1.36727087e-03,  9.74153528e-04,  5.25295499e-04, ...,
         -7.98493336e-05,  2.55382652e-04, -1.55450055e-03],
        [ 1.80715179e-03,  5.43495477e-04,  1.00418681e-04, ...,
         -1.61727093e-04,  2.24558709e-03,  6.41141212e-04],
        [-4.40021951e-04,  3.88964485e-04, -5.44459093e-04, ...,
         -2.80253302e-03, -7.27657709e-04, -1.42905920e-03],
        ...,
        [-4.18766053e-05,  9.98966609e-05, -6.54244748e-04, ...,
         -1.76434466e-04, -1.56196218e-06,  5.82488616e-04],
        [ 1.44038020e-03,  4.04670583e-04, -3.94844472e-04, ...,
         -1.67677862e-04,  7.00521617e-04,  2.84958304e-04],
        [-2.25426416e-05,  6.33407823e-04,  9.85764441e-04, ...,
          9.90042418e-04,  4.45906841e-04, -1.29504457e-03]]),
 'Wxh': array([[-6.33082199e-04,  1.87395428e-05,  8.60229599e-05, ...,
         -6.12018699e-04, -1.94850184e-03, -4.42349503e-04],
        [-3.59241168e-04, -1.22832266e-03,  7.50452282e-04, ...,
          1.70785258e-03

In [ ]:
inputs = createInputs("£ 400 xmas reward waiting computer randomly picked loyal mobile customers receive £ 400 reward 09066380611")
inputs

[array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[1

In [ ]:
def softmax(xs):
  # Applies the Softmax Function to the input array.
  return np.exp(xs) / sum(np.exp(xs))

In [ ]:
rnn.forward(inputs) # gives y and h

(array([[-4.89147174e-06],
        [-1.90589337e-06]]),
 array([[-6.41128508e-04],
        [-3.53147336e-04],
        [-1.51017791e-03],
        [ 1.90523966e-03],
        [ 3.77634735e-04],
        [ 6.62388363e-04],
        [-4.55322341e-05],
        [-6.33993232e-04],
        [ 2.31304410e-04],
        [-3.17930745e-04],
        [-7.35082369e-04],
        [-3.41240748e-04],
        [ 1.90454489e-03],
        [-2.01234337e-04],
        [-1.41392292e-03],
        [-1.20659491e-03],
        [-6.31108116e-04],
        [ 1.34892792e-03],
        [ 1.56005562e-03],
        [-1.09773588e-03],
        [-4.42815319e-04],
        [-3.00203404e-04],
        [-8.84488052e-04],
        [-3.33966865e-04],
        [ 3.91388764e-04],
        [ 1.58193101e-04],
        [ 2.25114517e-04],
        [ 6.30751679e-04],
        [ 7.25699245e-04],
        [ 5.78390145e-04],
        [ 1.16285227e-04],
        [-5.51622563e-04],
        [-1.04667862e-03],
        [-4.46028590e-04],
        [-9.67378163e-04],

In [ ]:
rnn.forward(inputs)[0] # y alone

array([[-4.89147174e-06],
       [-1.90589337e-06]])

In [ ]:
softmax(rnn.forward(inputs)[0])

array([[0.49999925],
       [0.50000075]])

In [ ]:
inputs = createInputs("offer price")
softmax(rnn.forward(inputs)[0])

array([[0.49999925],
       [0.50000075]])

In [ ]:

y_train = pd.DataFrame(y_train)  # Convert to DataFrame
y_train.reset_index(drop=True, inplace=True)  # Reset index directly
y_train = y_train.iloc[:,0].values.tolist()
for i in range(len(y_train)):
  if y_train[i]=='spam':
    y_train[i] = True
  else:
    y_train[i]= False

In [ ]:
y_test = pd.DataFrame(y_test)  # Convert to DataFrame
y_test.reset_index(drop=True, inplace=True)  # Reset index directly
y_test = y_test.iloc[:,0].values.tolist()
for i in range(len(y_test)):
  if y_test[i]=='spam':
    y_test[i] = True
  else:
    y_test[i]= False

In [ ]:
import random

def processData(x,y, backprop=True):
  '''
  Returns the RNN's loss and accuracy for the given data.
  - data is a dictionary mapping text to True or False.
  - backprop determines if the backward phase should be run.
  '''
  # items = list(data.items())
  # random.shuffle(items)
  x = pd.DataFrame(x)  # Convert to DataFrame
  x.reset_index(drop=True, inplace=True)  # Reset index directly
  x = x.iloc[:,0].values.tolist()
  # y.reset_index(inplace=True)

  loss = 0
  num_correct = 0
  # index = [x.index]
  for i in range(len(x)):
    inputs = createInputs(x[i])
    target = int(y[i])

    # Forward
    out, _ = rnn.forward(inputs)
    probs = softmax(out)

    # Calculate loss / accuracy
    loss -= np.log(probs[target])
    num_correct += int(np.argmax(probs) == target)

    if backprop:
      # Build dL/dy
      d_L_d_y = probs
      d_L_d_y[target] -= 1

      # Backward
      rnn.backprop(d_L_d_y)

  return loss / len(x), num_correct / len(x)

In [ ]:
# Training loop
for epoch in range(5):
  train_loss, train_acc = processData(x_train,y_train)

  print('--- Epoch %d' % (epoch + 1))
  print('Train:\tLoss %.3f | Accuracy: %.3f' % (train_loss, train_acc))

  test_loss, test_acc = processData(x_test,y_test, backprop=False)
  print('Test:\tLoss %.3f | Accuracy: %.3f' % (test_loss, test_acc))

--- Epoch 1
Train:	Loss 0.009 | Accuracy: 0.999
Test:	Loss 0.000 | Accuracy: 1.000
--- Epoch 2
Train:	Loss 0.008 | Accuracy: 0.999
Test:	Loss 0.001 | Accuracy: 1.000
--- Epoch 3
Train:	Loss 0.007 | Accuracy: 0.999
Test:	Loss 0.001 | Accuracy: 1.000
--- Epoch 4
Train:	Loss 0.007 | Accuracy: 0.999
Test:	Loss 0.001 | Accuracy: 1.000
--- Epoch 5
Train:	Loss 0.007 | Accuracy: 0.999
Test:	Loss 0.001 | Accuracy: 1.000


In [ ]:
rnn.__dict__

{'Whh': array([[ 1.25001816e-02, -1.71098407e-03, -2.29225352e-05, ...,
          5.80482470e-04, -1.19024461e-02, -5.71934611e-03],
        [-6.22522283e-04,  1.12403145e-03,  2.15125458e-04, ...,
         -3.04204128e-04,  4.90893710e-03,  1.53445931e-03],
        [-9.52488431e-04,  5.10558553e-04, -5.21202013e-04, ...,
         -2.83252940e-03, -1.64618533e-04, -1.24237121e-03],
        ...,
        [ 5.17513004e-04, -3.31141440e-05, -6.80575118e-04, ...,
         -1.44082749e-04, -6.15744289e-04,  3.78508416e-04],
        [-1.08468401e-02,  3.37177809e-03,  2.13574593e-04, ...,
         -8.97786062e-04,  1.41113077e-02,  4.89264256e-03],
        [-3.86783863e-03,  1.55221050e-03,  1.16794746e-03, ...,
          7.64946253e-04,  4.66104484e-03,  1.18918828e-04]]),
 'Wxh': array([[-9.69671889e-02,  1.87395428e-05,  8.60229599e-05, ...,
         -6.12018699e-04, -1.94850184e-03, -4.42349503e-04],
        [ 2.24889587e-02, -1.22832266e-03,  7.50452282e-04, ...,
          1.70785258e-03

In [ ]:
inputs = createInputs("gift card")
out, _ = rnn.forward(inputs)
softmax(out)

array([[8.80128156e-04],
       [9.99119872e-01]])

In [ ]:
inputs = createInputs("offer coupon")
out, _ = rnn.forward(inputs)
softmax(out)

array([[8.80128156e-04],
       [9.99119872e-01]])

In [ ]:
inputs = createInputs("how are you")
out, _ = rnn.forward(inputs)
softmax(out)

# Out of Vocab Word

array([[8.23153510e-04],
       [9.99176846e-01]])