<a href="https://colab.research.google.com/github/Asma-malica/DL/blob/main/DL_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# tensor is a multidimensional array
# vector is a  tensor
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0     #greyscale image  --> pixel length --> so only  255

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [ ]:
# Sequential is useful for stacking layers where each layer has one input tensor and one output tensor

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2), # 2% it will dropout (unwanted data's dropout)
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.15922193, -0.9246739 ,  0.45922562, -0.07114114,  0.5813159 ,
         0.16862674, -0.56819606,  0.13585645,  0.7077533 , -0.3228556 ]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy() #softmax --> converts all the above values into a postive range

array([[0.07613476, 0.03541208, 0.1413095 , 0.08314497, 0.15965939,
        0.10567343, 0.05057871, 0.10226662, 0.18117803, 0.06464244]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.2474017

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2984 - accuracy: 0.9141
Epoch 2/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1443 - accuracy: 0.9580
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1073 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0896 - accuracy: 0.9720
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0744 - accuracy: 0.9770
